# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore Hello-world/hello-world.sln
    - name: Build
      run: dotnet build Hello-world/hello-world.sln --no-restore
    - name: Test
      run: dotnet test Hello-world/hello-world.sln --no-build --verbosity normal
    - name: Create the package
      run: dotnet pack --configuration Release Hello-world/hello-world.sln
    - name: Artifacts
      run: publish
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test
        path: artifacts
    

